#include<stdio.h>
#include<math.h>
#include"recur.c"
#include <gsl/gsl_integration.h>
#include"gsl_integration.c"
#define NMAX 100
#include"timer.h"
#include"timer.c"
#include"adjust.c"

/* The integral is evaluated for n=0 to n=100 using both a derived recursion formula
 * and the GSL general integrator. The values of both are stored in their own 
 * respective arrays. The values and their absolute error are printed in order to
 * compare the accuracy of the two methods. Then, both functions are timed to 
 * determine which one is faster at generating the results. Finally, the timings of
 * the two functions are divided to provide a ratio describing the difference in 
 * efficiency of the two methods.
*/
int main (void)
{
    double vals1[NMAX + 1], vals2[NMAX + 1], time1a, time1b, time2a, time2b, tmin = 1., tmax = 2.;      // Initializing all the "double" variables for use in the program//
    int nmin = 0, nmax = NMAX, count1 = 1000, count2 = 800;

    integral_recur (nmin, nmax, vals1); // Recursion formula stores I(0) to I(100) in the array vals1//
    integral_gen (nmin, nmax, vals2);   // GSL integration algorithm stores I(0) to I(100) in the array vals2//

    printf
        ("      --n--       --Recur--        --GSL Integrator--   --Absolute Error*10^9--\n");
    int k;

    for (k = 0; k < 101; k++)
    {
        printf ("   %6d     %15.15f     %15.15f      %15.15f \n", k, vals1[k],
            vals2[k], fabs (1.e9 * (vals1[k] - vals2[k])));
    }                           // Prints the values for each term in the sequence as generated by both of the algorithms //
    int p;

    printf
        ("\n--Timing for recurrence function--\nTime per call (usec) Total Time (sec)      Count\n");
    do
    {
        timer_start ();         // The timer is started.
        for (p = 0; p < count1; p++)    // The function is called "count1" times.
        {
            integral_recur (nmin, nmax, vals1); // The recursion formula stores each of the sequence values in the array vals1//
        }
        time1a = timer_stop (); // The timer is stopped.
        time1b = time1a / count1;       // The time per function call is calculated as the total time divided by the number of function calls.
        printf (" %10.2f usec     %10.6f sec    %10d\n", time1b * 1.e6,
            time1a, count1);
        count1 = adjust_rep_count (count1, time1a, tmin, tmax); // The number of function calls "count1" is adjusted. 
    }
    while ((time1a > tmax) || (time1a < tmin)); // This is repeated until the total time is within the desired range.
    printf ("Time per recur function call = %f usec \n", time1b * 1.e6);
    printf
        ("\n--Timing for GSL integration function--\nTime per call (usec) Total Time (sec)      Count\n");
    do
    {
        timer_start ();         // The timer is started.
        for (p = 0; p < count2; p++)    // The function is called "count2" times.
        {
            integral_gen (nmin, nmax, vals2);   // The GSL integration formula stores each of the sequence values in the array vals1//
        }
        time2a = timer_stop (); // The timer is stopped.
        time2b = time2a / count2;       // The time per function call is calculated as the total time divided by the number of function calls.
        printf (" %10.2f usec     %10.6f sec    %10d\n", time2b * 1.e6,
            time2a, count2);
        count2 = adjust_rep_count (count2, time2a, tmin, tmax); // The number of function calls "count2" is adjusted. 
    }
    while ((time2a > tmax) || (time2a < tmin)); // This is repeated until the total time is within the desired range.
    printf ("Time per GSL function call = %f usec \n", time2b * 1.e6);

    printf ("Ratio of times Tgsl / Trecur = %f\n", time2b / time1b);    // The ratio of times per function call of each function is printed//
    return 0;
}
